### PR TITLE
Whitelisted formatting and lint check targets

### LINKED ISSUE #104: `shell/lint.sh` fails with exit code 1 without giving proper error
**Describe the bug**
I think the bug has to do with improper exclusion of `venv` folder by both `shell/format.sh` and `shell/lint.sh`, since on running `format.sh` the script starts formatting code install in virtual environment installed packages, i.e., in `venv` folder. If terminal session is closed before this process, then leads to `lint.sh` failing to pass as it includes `venv` directory "unformatted" code.

**To Reproduce**
I am using Windows system to format my code, No WSL and using VirtualEnv environment created using PyCharm (doesn't matter).

**Expected behavior**
`format.sh` and `lint.sh` should exclude `venv` folder in the operation.

**Would you like to help us fix it?**
Definitely.

### PR DESCRIPTION
**Pull request by adhadse**
Resolves #104.

The proposed solution intends to whitelist directories/files that are supposed to be formatted and lint checked.
From current scenario it looks that the bash scripts don't perform really well with PowerShell, so WSL is recommended for project development on Windows platform.

Other than that, `lint.sh` continues to fail with error "Broken 1 Paths" while the input argument are same as in `format.sh`. This is discussed in above  issue.

- [X] `format.sh` fixed
- [X] `lint.sh` fixed

---
The above issue was resolved by switching from `"${targets}"` to `${targets}`.

### CODE REVIEW

File: shell/format.sh [hunk 1]
```diff
@@ -1,15 +1,17 @@
...
+target_dir="${base_dir}/examples/ ${base_dir}/keras_nlp/"
+targets="${base_dir}/*.py ${base_dir}/examples/ ${base_dir}/keras_nlp/"
 
-isort --sl ${base_dir}
-black --line-length 80 ${base_dir}
+isort --sp "${base_dir}/setup.cfg" --sl ${targets}
+black --line-length 80 ${targets}
 
-for i in $(find ${base_dir} -name '*.py'); do
+for i in $(find ${target_dir} -name '*.py'); do
```
Comment (mattdangerw) [inline shell/format.sh:10]: Can you just you targets here? Prefer to avoid the duplicated variable above.

File: shell/lint.sh [hunk 2]
```diff
@@ -1,24 +1,28 @@
...
-black --check --line-length 80 "${base_dir}"
+
+black --check --line-length 80 "${targets}"
 if ! [ $? -eq 0 ]; then
   echo "Please run \"./shell/format.sh\" to format the code."
     exit 1
 fi
-for i in $(find "${base_dir}" -name '*.py'); do
-  if ! grep -q Copyright $i; then
+for i in $(find "${target_dir}" -name '*.py'); do
```
Comment (mattdangerw) [inline shell/lint.sh:24]: Same here, use targets, remove other variable.

**Review by mattdangerw — CHANGES_REQUESTED** [review]
Looks good! Few comments.

**Comment by adhadse** [comment]
Ready to Merge!!!

**Review by mattdangerw — APPROVED** [review]
Thanks! This looks good, approving. I will test out and merge shortly.
